## Numpy coding warm-up

### Please write down your name and EWU ID here:  Nate Wilson - 00958137

### Submit the finished notebook to Canvas by the deadline. 

You are allowed and encouraged to search and get help from any resource, but write down the code by your own hands. 

In [64]:
import numpy as np

**Your work**: Write one statement **into** the next cell that creates a $7 \times 6$ (ie., 7 rows by 6 columns)  ndarray of random numbers uniformly drawn from the range $[0,1)$. Save the array into a variable named as `a`. Below is the expected result. 
```
[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607]
 [0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362]
 [0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006]
 [0.11398436 0.82868133 0.04689632 0.62628715 0.54758616 0.819287  ]]
```

In [65]:
np.random.seed(10)

## Start your new code here
a = np.random.uniform(0,1,42).reshape(7,6)

## End of your code here

print(a)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607]
 [0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362]
 [0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006]
 [0.11398436 0.82868133 0.04689632 0.62628715 0.54758616 0.819287  ]]


**Your work**: Write statement **into** the next cell that creates  a $7 \times 6$ (ie., 7 rows by 6 columns) ndarray of random numbers  drawn from the Gaussian (normal) distribution with mean 0 and variance 1. Save the array into a variable named as `b`. Below is the expected result. 
```
[[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556]
 [ 0.26551159  0.10854853  0.00429143 -0.17460021  0.43302619  1.20303737]
 [-0.96506567  1.02827408  0.22863013  0.44513761 -1.13660221  0.13513688]
 [ 1.484537   -1.07980489 -1.97772828 -1.7433723   0.26607016  2.38496733]
 [ 1.12369125  1.67262221  0.09914922  1.39799638 -0.27124799  0.61320418]
 [-0.26731719 -0.54930901  0.1327083  -0.47614201  1.30847308  0.19501328]
 [ 0.40020999 -0.33763234  1.25647226 -0.7319695   0.66023155 -0.35087189]]
```

In [66]:
np.random.seed(10)

## Start your new code here
b = np.random.normal(0,1,42).reshape(7,6)

## End of your code here

print(b)

[[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556]
 [ 0.26551159  0.10854853  0.00429143 -0.17460021  0.43302619  1.20303737]
 [-0.96506567  1.02827408  0.22863013  0.44513761 -1.13660221  0.13513688]
 [ 1.484537   -1.07980489 -1.97772828 -1.7433723   0.26607016  2.38496733]
 [ 1.12369125  1.67262221  0.09914922  1.39799638 -0.27124799  0.61320418]
 [-0.26731719 -0.54930901  0.1327083  -0.47614201  1.30847308  0.19501328]
 [ 0.40020999 -0.33763234  1.25647226 -0.7319695   0.66023155 -0.35087189]]


**Your work**: Write one statement **into** the next cell that slices out the rows 3-5 and columns 2-4 of array `a`. Save the result in a variable named `c`. Below is the expected result.
```
[[0.54254437 0.14217005 0.37334076]
 [0.61776698 0.51313824 0.65039718]
 [0.90864888 0.31923609 0.09045935]]
```

In [67]:
## Start your new code here
c = a[3:6, 2:5]

## End of your code here

print(c)

[[0.54254437 0.14217005 0.37334076]
 [0.61776698 0.51313824 0.65039718]
 [0.90864888 0.31923609 0.09045935]]


**Your work**: Write one statement **into** the next cell that element-wise add `a` and `b`. Save the result in a variable named `d`. Below is the expected result.
```
[[ 2.10290715  0.73603092 -0.91175206  0.74042003  1.11984299 -0.49528892]
 [ 0.46357445  0.86907924  0.17340227 -0.0862604   1.11838601  2.15643072]
 [-0.9611174   1.54046634  1.04125109  1.05766368 -0.41484689  0.42701295]
 [ 2.40231112 -0.3652291  -1.43518391 -1.60120225  0.63941092  3.05910095]
 [ 1.56552443  2.10663621  0.71691619  1.91113462  0.37914919  1.21424314]
 [ 0.53790601 -0.02766186  1.04135718 -0.15690593  1.39893243  0.49571334]
 [ 0.51419435  0.49104899  1.30336858 -0.10568235  1.20781771  0.4684151 ]]
```

In [68]:
## Start your new code here
d = a + b


## End of your code here

print(d)

[[ 2.10290715  0.73603092 -0.91175206  0.74042003  1.11984299 -0.49528892]
 [ 0.46357445  0.86907924  0.17340227 -0.0862604   1.11838601  2.15643072]
 [-0.9611174   1.54046634  1.04125109  1.05766368 -0.41484689  0.42701295]
 [ 2.40231112 -0.3652291  -1.43518391 -1.60120225  0.63941092  3.05910095]
 [ 1.56552443  2.10663621  0.71691619  1.91113462  0.37914919  1.21424314]
 [ 0.53790601 -0.02766186  1.04135718 -0.15690593  1.39893243  0.49571334]
 [ 0.51419435  0.49104899  1.30336858 -0.10568235  1.20781771  0.4684151 ]]


**Your work**: Write one statement **into** the next cell that produce the transpose of `a`. Save the result in a variable named as `e`. Below is the expected result.
```
[[0.77132064 0.19806286 0.00394827 0.91777412 0.44183317 0.8052232
  0.11398436]
 [0.02075195 0.76053071 0.51219226 0.71457578 0.43401399 0.52164715
  0.82868133]
 [0.63364823 0.16911084 0.81262096 0.54254437 0.61776698 0.90864888
  0.04689632]
 [0.74880388 0.08833981 0.61252607 0.14217005 0.51313824 0.31923609
  0.62628715]
 [0.49850701 0.68535982 0.72175532 0.37334076 0.65039718 0.09045935
  0.54758616]
 [0.22479665 0.95339335 0.29187607 0.67413362 0.60103895 0.30070006
  0.819287  ]]
```

In [69]:
## Start your new code here
e = a.T

## End of your code here

print(e)

[[0.77132064 0.19806286 0.00394827 0.91777412 0.44183317 0.8052232
  0.11398436]
 [0.02075195 0.76053071 0.51219226 0.71457578 0.43401399 0.52164715
  0.82868133]
 [0.63364823 0.16911084 0.81262096 0.54254437 0.61776698 0.90864888
  0.04689632]
 [0.74880388 0.08833981 0.61252607 0.14217005 0.51313824 0.31923609
  0.62628715]
 [0.49850701 0.68535982 0.72175532 0.37334076 0.65039718 0.09045935
  0.54758616]
 [0.22479665 0.95339335 0.29187607 0.67413362 0.60103895 0.30070006
  0.819287  ]]


**Your work**: Write one statement **into** the next cell that does matrix multiplication of `e` and `b`. Save the result in a variable named as `f`. Below is the expected result.
```
[[ 2.7651792  -0.1555294  -2.71146892 -1.48846541  1.81374296  2.26022429]
 [ 1.47597677  0.01207588 -0.1714663  -1.39893598  1.06214948  2.75056599]
 [ 1.37990318  1.23967504 -1.62496986 -0.22230445  0.74000293  1.69049266]
 [ 1.38239924  1.49299396 -0.41779948  0.11004166  0.53715962  0.14608625]
 [ 1.62928681  1.62328933 -0.57628538  0.01193017  0.18898359  1.67782151]
 [ 2.19445664  0.39999365 -0.48092151 -1.11630694  1.17148483  2.77206021]]
```

In [70]:
## Start your new code here
f = e @ b

## End of your code here

print(f)

[[ 2.7651792  -0.1555294  -2.71146892 -1.48846541  1.81374296  2.26022429]
 [ 1.47597677  0.01207588 -0.1714663  -1.39893598  1.06214948  2.75056599]
 [ 1.37990318  1.23967504 -1.62496986 -0.22230445  0.74000293  1.69049266]
 [ 1.38239924  1.49299396 -0.41779948  0.11004166  0.53715962  0.14608625]
 [ 1.62928681  1.62328933 -0.57628538  0.01193017  0.18898359  1.67782151]
 [ 2.19445664  0.39999365 -0.48092151 -1.11630694  1.17148483  2.77206021]]


**Your work**: Write one statement **into** the next cell that reshapes the array `f` into a new shape of 
$12\times 3$. Save the result in a variable named as `g`. Below is the expected result.
```
[[ 2.7651792  -0.1555294  -2.71146892]
 [-1.48846541  1.81374296  2.26022429]
 [ 1.47597677  0.01207588 -0.1714663 ]
 [-1.39893598  1.06214948  2.75056599]
 [ 1.37990318  1.23967504 -1.62496986]
 [-0.22230445  0.74000293  1.69049266]
 [ 1.38239924  1.49299396 -0.41779948]
 [ 0.11004166  0.53715962  0.14608625]
 [ 1.62928681  1.62328933 -0.57628538]
 [ 0.01193017  0.18898359  1.67782151]
 [ 2.19445664  0.39999365 -0.48092151]
 [-1.11630694  1.17148483  2.77206021]]
```

In [71]:
## Start your new code here
g = np.reshape(f, (12,3))

## End of your code here

print(g)

[[ 2.7651792  -0.1555294  -2.71146892]
 [-1.48846541  1.81374296  2.26022429]
 [ 1.47597677  0.01207588 -0.1714663 ]
 [-1.39893598  1.06214948  2.75056599]
 [ 1.37990318  1.23967504 -1.62496986]
 [-0.22230445  0.74000293  1.69049266]
 [ 1.38239924  1.49299396 -0.41779948]
 [ 0.11004166  0.53715962  0.14608625]
 [ 1.62928681  1.62328933 -0.57628538]
 [ 0.01193017  0.18898359  1.67782151]
 [ 2.19445664  0.39999365 -0.48092151]
 [-1.11630694  1.17148483  2.77206021]]


**Your work**: Write one statement **into** the next cell that multiple array `g` with the scaler $3$. Save the result in a variable named as `h`. Below is the expected result.
```
[[ 8.29553761 -0.46658819 -8.13440676]
 [-4.46539622  5.44122889  6.78067286]
 [ 4.42793032  0.03622763 -0.5143989 ]
 [-4.19680794  3.18644843  8.25169797]
 [ 4.13970955  3.71902512 -4.87490959]
 [-0.66691335  2.22000879  5.07147798]
 [ 4.14719772  4.47898189 -1.25339844]
 [ 0.33012497  1.61147885  0.43825876]
 [ 4.88786043  4.869868   -1.72885615]
 [ 0.0357905   0.56695077  5.03346453]
 [ 6.58336992  1.19998095 -1.44276454]
 [-3.34892081  3.5144545   8.31618062]]
```

In [74]:
## Start your new code here
h = 3 * g

## End of your code here

print(h)

[[ 8.29553761 -0.46658819 -8.13440676]
 [-4.46539622  5.44122889  6.78067286]
 [ 4.42793032  0.03622763 -0.5143989 ]
 [-4.19680794  3.18644843  8.25169797]
 [ 4.13970955  3.71902512 -4.87490959]
 [-0.66691335  2.22000879  5.07147798]
 [ 4.14719772  4.47898189 -1.25339844]
 [ 0.33012497  1.61147885  0.43825876]
 [ 4.88786043  4.869868   -1.72885615]
 [ 0.0357905   0.56695077  5.03346453]
 [ 6.58336992  1.19998095 -1.44276454]
 [-3.34892081  3.5144545   8.31618062]]


**Your work**: Write one statement **into** the next cell that adds a new column of all $1$ into
the array `h`, i.e., the newly added column of all $1$ becomes the $0$th column. Save the resuling new array 
as `i` (without changing `h`). Below is the expected result.
```
[[ 1.          8.29553761 -0.46658819 -8.13440676]
 [ 1.         -4.46539622  5.44122889  6.78067286]
 [ 1.          4.42793032  0.03622763 -0.5143989 ]
 [ 1.         -4.19680794  3.18644843  8.25169797]
 [ 1.          4.13970955  3.71902512 -4.87490959]
 [ 1.         -0.66691335  2.22000879  5.07147798]
 [ 1.          4.14719772  4.47898189 -1.25339844]
 [ 1.          0.33012497  1.61147885  0.43825876]
 [ 1.          4.88786043  4.869868   -1.72885615]
 [ 1.          0.0357905   0.56695077  5.03346453]
 [ 1.          6.58336992  1.19998095 -1.44276454]
 [ 1.         -3.34892081  3.5144545   8.31618062]]
```
Hint: Use np.insert() method. Search and read the API's document. 

In [76]:
## Start your new code here
i = np.insert(h, 0, np.ones(h.shape[0]), axis = 1)

## End of your code here

print(i)

[[ 1.          8.29553761 -0.46658819 -8.13440676]
 [ 1.         -4.46539622  5.44122889  6.78067286]
 [ 1.          4.42793032  0.03622763 -0.5143989 ]
 [ 1.         -4.19680794  3.18644843  8.25169797]
 [ 1.          4.13970955  3.71902512 -4.87490959]
 [ 1.         -0.66691335  2.22000879  5.07147798]
 [ 1.          4.14719772  4.47898189 -1.25339844]
 [ 1.          0.33012497  1.61147885  0.43825876]
 [ 1.          4.88786043  4.869868   -1.72885615]
 [ 1.          0.0357905   0.56695077  5.03346453]
 [ 1.          6.58336992  1.19998095 -1.44276454]
 [ 1.         -3.34892081  3.5144545   8.31618062]]
